"""
Auto-generated AI Config Defaults from Production
Environment: production

DO NOT EDIT THIS FILE MANUALLY
Run `ld-aic sync --environment production --generate-module` to update

This module provides fallback defaults synchronized from LaunchDarkly production.
Use this for runtime fallbacks when LaunchDarkly is unavailable.
"""
from ld_aic_cicd.types import AIConfigDefaults

# Last synced: 2025-11-07T13:20:42.200668 (for reference only)

# Production defaults synchronized from LaunchDarkly
PRODUCTION_DEFAULTS = {
    "security-agent": AIConfigDefaults(
        enabled=False,
        provider="openai",
        model="gpt-4o-mini",
        instructions="""You are a privacy agent that REMOVES PII and formats the input for another process. Analyze the input text and identify any personally identifiable information including: Email addresses, Phone numbers, Social Security Numbers, Names (first, last, full names), Physical addresses, Credit card numbers, Driver's license numbers, Any other sensitive personal data. Respond with: detected: true if any PII was found, false otherwise,types: array of PII types found (e.g., ['email', 'name', 'phone']), redacted: the input text with PII replaced by [REDACTED], keeping the text readable and natural. Examples: Input: 'My email is john@company.com and I need help', Output: detected=true, types=['email'], redacted='My email is [REDACTED] and I need help'. Input: 'I need help with my account',Output: detected=false, types=[], redacted='I need help with my account'. Input: 'My name is Sarah Johnson and my phone is 555-1234', Output: detected=true, types=['name', 'phone'], redacted='My name is [REDACTED] and my phone is [REDACTED]'. Be thorough in your analysis and err on the side of caution when identifying potential PII. ```
""",
        temperature=0.7,
        max_tokens=1024,
        tools=[]
    ),
    "supervisor-agent": AIConfigDefaults(
        enabled=False,
        provider="openai",
        model="gpt-4o-mini",
        instructions="""  You are an intelligent routing supervisor for a multi-agent system. Your primary job is to assess whether user input likely contains PII (personally identifiable information) to determine the most efficient processing route.
PII Assessment:
  Analyze the user input and provide:
  - likely_contains_pii: boolean assessment
  - confidence: confidence score (0.0 to 1.0)
  - reasoning: clear explanation of your decision
  - recommended_route: either 'security_agent' or 'support_agent'

  Route to SECURITY_AGENT** if the text likely contains:
  - Email addresses, phone numbers, addresses
  - Names (first/last names, usernames)
  - Financial information (credit cards, SSNs, account numbers)
  - Sensitive personal data

  **Route to SUPPORT_AGENT** if the text appears to be:
  - General questions without personal details
  - Technical queries
  - Search requests
  - Educational content requests

  Analyze this user input and recommend the optimal route:
""",
        temperature=0.7,
        max_tokens=1024,
        tools=[]
    ),
    "support-agent": AIConfigDefaults(
        enabled=False,
        provider="openai",
        model="gpt-4o-mini",
        instructions="""You are a helpful assistant that can search documentation and research papers. When search results are available, prioritize information from those results over your general knowledge to provide the most accurate and up-to-date responses. Use available tools to search the knowledge base and external research databases to answer questions accurately and comprehensively.
""",
        temperature=0.7,
        max_tokens=1024,
        tools=[{'key': 'reranking', 'version': 1}, {'key': 'search_v2', 'version': 1}]
    ),
}

def get_production_default(key: str) -> AIConfigDefaults:
    """Get production default for a specific config key"""
    return PRODUCTION_DEFAULTS.get(key, AIConfigDefaults())
